name: textify
description: "A cross-platform Flutter package that extracts text from clean digital images using standard fonts, run offline with no external dependencies."

version: 0.4.2
homepage: https://github.com/vteam-com/textify

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  assets:
    - assets/matrices.json
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/CourierPrime-Regular.ttf
    - assets/test/
